# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(1009, 759)
        self.label_1 = QtWidgets.QLabel(dialog)
        self.label_1.setGeometry(QtCore.QRect(110, 100, 261, 91))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(24)
        self.label_1.setFont(font)
        self.label_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(dialog)
        self.label_2.setGeometry(QtCore.QRect(610, 100, 261, 91))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.video1 = QtWidgets.QLabel(dialog)
        self.video1.setGeometry(QtCore.QRect(50, 170, 391, 481))
        self.video1.setObjectName("video1")
        self.video2 = QtWidgets.QLabel(dialog)
        self.video2.setGeometry(QtCore.QRect(560, 170, 401, 481))
        self.video2.setObjectName("video2")
        self.pushButton1 = QtWidgets.QPushButton(dialog)
        self.pushButton1.setGeometry(QtCore.QRect(200, 670, 93, 28))
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton2 = QtWidgets.QPushButton(dialog)
        self.pushButton2.setGeometry(QtCore.QRect(720, 670, 93, 28))
        self.pushButton2.setObjectName("pushButton2")
        self.carnum1 = QtWidgets.QLabel(dialog)
        self.carnum1.setGeometry(QtCore.QRect(391, 190, 71, 20))
        self.carnum1.setObjectName("carnum1")
        self.label_3 = QtWidgets.QLabel(dialog)
        self.label_3.setGeometry(QtCore.QRect(301, 190, 91, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(dialog)
        self.label_4.setGeometry(QtCore.QRect(800, 190, 91, 20))
        self.label_4.setObjectName("label_4")
        self.carnum2 = QtWidgets.QLabel(dialog)
        self.carnum2.setGeometry(QtCore.QRect(890, 190, 71, 20))
        self.carnum2.setObjectName("carnum2")

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Dialog"))
        self.label_1.setText(_translate("dialog", "停车场-入口A"))
        self.label_2.setText(_translate("dialog", "停车场-出口A"))
        self.video1.setText(_translate("dialog", "TextLabel"))
        self.video2.setText(_translate("dialog", "TextLabel"))
        self.pushButton1.setText(_translate("dialog", "查看记录"))
        self.pushButton2.setText(_translate("dialog", "查看记录"))
        self.carnum1.setText(_translate("dialog", "TextLabel"))
        self.label_3.setText(_translate("dialog", "入口车流量："))
        self.label_4.setText(_translate("dialog", "出口车流量："))
        self.carnum2.setText(_translate("dialog", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog = QtWidgets.QDialog()
    ui = Ui_dialog()
    ui.setupUi(dialog)
    dialog.show()
    sys.exit(app.exec_())
