# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mm1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(1009, 759)
        dialog.setStyleSheet("#dialog {background-image: url(:/back1.png)}")
        self.label_1 = QtWidgets.QLabel(dialog)
        self.label_1.setGeometry(QtCore.QRect(250, 60, 261, 91))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(24)
        self.label_1.setFont(font)
        self.label_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.video1 = QtWidgets.QLabel(dialog)
        self.video1.setGeometry(QtCore.QRect(50, 170, 611, 431))
        self.video1.setObjectName("video1")
        self.video2 = QtWidgets.QLabel(dialog)
        self.video2.setGeometry(QtCore.QRect(730, 80, 231, 571))
        self.video2.setObjectName("video2")
        self.pushButton = QtWidgets.QPushButton(dialog)
        self.pushButton.setGeometry(QtCore.QRect(810, 570, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.carnum1 = QtWidgets.QLabel(dialog)
        self.carnum1.setGeometry(QtCore.QRect(570, 190, 71, 20))
        self.carnum1.setObjectName("carnum1")
        self.label_3 = QtWidgets.QLabel(dialog)
        self.label_3.setGeometry(QtCore.QRect(480, 190, 91, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(dialog)
        self.label_4.setGeometry(QtCore.QRect(800, 120, 141, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.carnum2 = QtWidgets.QLabel(dialog)
        self.carnum2.setGeometry(QtCore.QRect(860, 180, 101, 16))
        self.carnum2.setObjectName("carnum2")
        self.label = QtWidgets.QLabel(dialog)
        self.label.setGeometry(QtCore.QRect(770, 180, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(dialog)
        self.label_2.setGeometry(QtCore.QRect(770, 200, 72, 15))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(dialog)
        self.label_5.setGeometry(QtCore.QRect(860, 200, 91, 16))
        self.label_5.setObjectName("label_5")
        self.backButton = QtWidgets.QPushButton(dialog)
        self.backButton.setGeometry(QtCore.QRect(20, 30, 93, 28))
        self.backButton.setObjectName("backButton")

        self.retranslateUi(dialog)
        self.pushButton.clicked.connect(dialog.check_button_clicked) # type: ignore
        self.backButton.clicked.connect(dialog.back_to) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Dialog"))
        self.label_1.setText(_translate("dialog", "停车场-入口A"))
        self.video1.setText(_translate("dialog", "TextLabel"))
        self.video2.setText(_translate("dialog", "TextLabel"))
        self.pushButton.setText(_translate("dialog", "查看记录"))
        self.carnum1.setText(_translate("dialog", "TextLabel"))
        self.label_3.setText(_translate("dialog", "入口车流量："))
        self.label_4.setText(_translate("dialog", "入场车辆信息"))
        self.carnum2.setText(_translate("dialog", "TextLabel"))
        self.label.setText(_translate("dialog", "车牌号："))
        self.label_2.setText(_translate("dialog", "车型："))
        self.label_5.setText(_translate("dialog", "TextLabel"))
        self.backButton.setText(_translate("dialog", "返回主菜单"))
import data.background_image_rc
